import typing_extensions

from wikimedia_python_sdk.paths import PathValues
from wikimedia_python_sdk.apis.paths.feed_availability import FeedAvailability
from wikimedia_python_sdk.apis.paths.media_math_check_type import MediaMathCheckType
from wikimedia_python_sdk.apis.paths.media_math_formula_hash import MediaMathFormulaHash
from wikimedia_python_sdk.apis.paths.media_math_render_format_hash import MediaMathRenderFormatHash
from wikimedia_python_sdk.apis.paths.metrics_bytes_difference_absolute_aggregate_project_editor_type_page_type_granularity_start_end import MetricsBytesDifferenceAbsoluteAggregateProjectEditorTypePageTypeGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_bytes_difference_absolute_per_page_project_page_title_editor_type_granularity_start_end import MetricsBytesDifferenceAbsolutePerPageProjectPageTitleEditorTypeGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_bytes_difference_net_aggregate_project_editor_type_page_type_granularity_start_end import MetricsBytesDifferenceNetAggregateProjectEditorTypePageTypeGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_bytes_difference_net_per_page_project_page_title_editor_type_granularity_start_end import MetricsBytesDifferenceNetPerPageProjectPageTitleEditorTypeGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_edited_pages_aggregate_project_editor_type_page_type_activity_level_granularity_start_end import MetricsEditedPagesAggregateProjectEditorTypePageTypeActivityLevelGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_edited_pages_new_project_editor_type_page_type_granularity_start_end import MetricsEditedPagesNewProjectEditorTypePageTypeGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_edited_pages_top_by_absolute_bytes_difference_project_editor_type_page_type_year_month_day import MetricsEditedPagesTopByAbsoluteBytesDifferenceProjectEditorTypePageTypeYearMonthDay
from wikimedia_python_sdk.apis.paths.metrics_edited_pages_top_by_edits_project_editor_type_page_type_year_month_day import MetricsEditedPagesTopByEditsProjectEditorTypePageTypeYearMonthDay
from wikimedia_python_sdk.apis.paths.metrics_edited_pages_top_by_net_bytes_difference_project_editor_type_page_type_year_month_day import MetricsEditedPagesTopByNetBytesDifferenceProjectEditorTypePageTypeYearMonthDay
from wikimedia_python_sdk.apis.paths.metrics_editors_aggregate_project_editor_type_page_type_activity_level_granularity_start_end import MetricsEditorsAggregateProjectEditorTypePageTypeActivityLevelGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_editors_top_by_absolute_bytes_difference_project_editor_type_page_type_year_month_day import MetricsEditorsTopByAbsoluteBytesDifferenceProjectEditorTypePageTypeYearMonthDay
from wikimedia_python_sdk.apis.paths.metrics_editors_top_by_edits_project_editor_type_page_type_year_month_day import MetricsEditorsTopByEditsProjectEditorTypePageTypeYearMonthDay
from wikimedia_python_sdk.apis.paths.metrics_editors_top_by_net_bytes_difference_project_editor_type_page_type_year_month_day import MetricsEditorsTopByNetBytesDifferenceProjectEditorTypePageTypeYearMonthDay
from wikimedia_python_sdk.apis.paths.metrics_edits_aggregate_project_editor_type_page_type_granularity_start_end import MetricsEditsAggregateProjectEditorTypePageTypeGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_edits_per_page_project_page_title_editor_type_granularity_start_end import MetricsEditsPerPageProjectPageTitleEditorTypeGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_legacy_pagecounts_aggregate_project_access_site_granularity_start_end import MetricsLegacyPagecountsAggregateProjectAccessSiteGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_pageviews_aggregate_project_access_agent_granularity_start_end import MetricsPageviewsAggregateProjectAccessAgentGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_pageviews_per_article_project_access_agent_article_granularity_start_end import MetricsPageviewsPerArticleProjectAccessAgentArticleGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_pageviews_top_by_country_project_access_year_month import MetricsPageviewsTopByCountryProjectAccessYearMonth
from wikimedia_python_sdk.apis.paths.metrics_pageviews_top_project_access_year_month_day import MetricsPageviewsTopProjectAccessYearMonthDay
from wikimedia_python_sdk.apis.paths.metrics_registered_users_new_project_granularity_start_end import MetricsRegisteredUsersNewProjectGranularityStartEnd
from wikimedia_python_sdk.apis.paths.metrics_unique_devices_project_access_site_granularity_start_end import MetricsUniqueDevicesProjectAccessSiteGranularityStartEnd
from wikimedia_python_sdk.apis.paths.transform_html_from_from_lang_to_to_lang import TransformHtmlFromFromLangToToLang
from wikimedia_python_sdk.apis.paths.transform_html_from_from_lang_to_to_lang_provider import TransformHtmlFromFromLangToToLangProvider
from wikimedia_python_sdk.apis.paths.transform_list_tool_tool import TransformListToolTool
from wikimedia_python_sdk.apis.paths.transform_list_tool_tool_from import TransformListToolToolFrom
from wikimedia_python_sdk.apis.paths.transform_list_tool_tool_from_to import TransformListToolToolFromTo
from wikimedia_python_sdk.apis.paths.transform_word_from_from_lang_to_to_lang_word import TransformWordFromFromLangToToLangWord
from wikimedia_python_sdk.apis.paths.transform_word_from_from_lang_to_to_lang_word_provider import TransformWordFromFromLangToToLangWordProvider
from wikimedia_python_sdk.apis.paths.transform_list_languagepairs import TransformListLanguagepairs
from wikimedia_python_sdk.apis.paths.transform_list_pair_from_to import TransformListPairFromTo

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.FEED_AVAILABILITY: FeedAvailability,
        PathValues.MEDIA_MATH_CHECK_TYPE: MediaMathCheckType,
        PathValues.MEDIA_MATH_FORMULA_HASH: MediaMathFormulaHash,
        PathValues.MEDIA_MATH_RENDER_FORMAT_HASH: MediaMathRenderFormatHash,
        PathValues.METRICS_BYTESDIFFERENCE_ABSOLUTE_AGGREGATE_PROJECT_EDITORTYPE_PAGETYPE_GRANULARITY_START_END: MetricsBytesDifferenceAbsoluteAggregateProjectEditorTypePageTypeGranularityStartEnd,
        PathValues.METRICS_BYTESDIFFERENCE_ABSOLUTE_PERPAGE_PROJECT_PAGETITLE_EDITORTYPE_GRANULARITY_START_END: MetricsBytesDifferenceAbsolutePerPageProjectPageTitleEditorTypeGranularityStartEnd,
        PathValues.METRICS_BYTESDIFFERENCE_NET_AGGREGATE_PROJECT_EDITORTYPE_PAGETYPE_GRANULARITY_START_END: MetricsBytesDifferenceNetAggregateProjectEditorTypePageTypeGranularityStartEnd,
        PathValues.METRICS_BYTESDIFFERENCE_NET_PERPAGE_PROJECT_PAGETITLE_EDITORTYPE_GRANULARITY_START_END: MetricsBytesDifferenceNetPerPageProjectPageTitleEditorTypeGranularityStartEnd,
        PathValues.METRICS_EDITEDPAGES_AGGREGATE_PROJECT_EDITORTYPE_PAGETYPE_ACTIVITYLEVEL_GRANULARITY_START_END: MetricsEditedPagesAggregateProjectEditorTypePageTypeActivityLevelGranularityStartEnd,
        PathValues.METRICS_EDITEDPAGES_NEW_PROJECT_EDITORTYPE_PAGETYPE_GRANULARITY_START_END: MetricsEditedPagesNewProjectEditorTypePageTypeGranularityStartEnd,
        PathValues.METRICS_EDITEDPAGES_TOPBYABSOLUTEBYTESDIFFERENCE_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditedPagesTopByAbsoluteBytesDifferenceProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITEDPAGES_TOPBYEDITS_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditedPagesTopByEditsProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITEDPAGES_TOPBYNETBYTESDIFFERENCE_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditedPagesTopByNetBytesDifferenceProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITORS_AGGREGATE_PROJECT_EDITORTYPE_PAGETYPE_ACTIVITYLEVEL_GRANULARITY_START_END: MetricsEditorsAggregateProjectEditorTypePageTypeActivityLevelGranularityStartEnd,
        PathValues.METRICS_EDITORS_TOPBYABSOLUTEBYTESDIFFERENCE_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditorsTopByAbsoluteBytesDifferenceProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITORS_TOPBYEDITS_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditorsTopByEditsProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITORS_TOPBYNETBYTESDIFFERENCE_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditorsTopByNetBytesDifferenceProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITS_AGGREGATE_PROJECT_EDITORTYPE_PAGETYPE_GRANULARITY_START_END: MetricsEditsAggregateProjectEditorTypePageTypeGranularityStartEnd,
        PathValues.METRICS_EDITS_PERPAGE_PROJECT_PAGETITLE_EDITORTYPE_GRANULARITY_START_END: MetricsEditsPerPageProjectPageTitleEditorTypeGranularityStartEnd,
        PathValues.METRICS_LEGACY_PAGECOUNTS_AGGREGATE_PROJECT_ACCESSSITE_GRANULARITY_START_END: MetricsLegacyPagecountsAggregateProjectAccessSiteGranularityStartEnd,
        PathValues.METRICS_PAGEVIEWS_AGGREGATE_PROJECT_ACCESS_AGENT_GRANULARITY_START_END: MetricsPageviewsAggregateProjectAccessAgentGranularityStartEnd,
        PathValues.METRICS_PAGEVIEWS_PERARTICLE_PROJECT_ACCESS_AGENT_ARTICLE_GRANULARITY_START_END: MetricsPageviewsPerArticleProjectAccessAgentArticleGranularityStartEnd,
        PathValues.METRICS_PAGEVIEWS_TOPBYCOUNTRY_PROJECT_ACCESS_YEAR_MONTH: MetricsPageviewsTopByCountryProjectAccessYearMonth,
        PathValues.METRICS_PAGEVIEWS_TOP_PROJECT_ACCESS_YEAR_MONTH_DAY: MetricsPageviewsTopProjectAccessYearMonthDay,
        PathValues.METRICS_REGISTEREDUSERS_NEW_PROJECT_GRANULARITY_START_END: MetricsRegisteredUsersNewProjectGranularityStartEnd,
        PathValues.METRICS_UNIQUEDEVICES_PROJECT_ACCESSSITE_GRANULARITY_START_END: MetricsUniqueDevicesProjectAccessSiteGranularityStartEnd,
        PathValues.TRANSFORM_HTML_FROM_FROM_LANG_TO_TO_LANG: TransformHtmlFromFromLangToToLang,
        PathValues.TRANSFORM_HTML_FROM_FROM_LANG_TO_TO_LANG_PROVIDER: TransformHtmlFromFromLangToToLangProvider,
        PathValues.TRANSFORM_LIST_TOOL_TOOL: TransformListToolTool,
        PathValues.TRANSFORM_LIST_TOOL_TOOL_FROM: TransformListToolToolFrom,
        PathValues.TRANSFORM_LIST_TOOL_TOOL_FROM_TO: TransformListToolToolFromTo,
        PathValues.TRANSFORM_WORD_FROM_FROM_LANG_TO_TO_LANG_WORD: TransformWordFromFromLangToToLangWord,
        PathValues.TRANSFORM_WORD_FROM_FROM_LANG_TO_TO_LANG_WORD_PROVIDER: TransformWordFromFromLangToToLangWordProvider,
        PathValues.TRANSFORM_LIST_LANGUAGEPAIRS: TransformListLanguagepairs,
        PathValues.TRANSFORM_LIST_PAIR_FROM_TO: TransformListPairFromTo,
    }
)

path_to_api = PathToApi(
    {
        PathValues.FEED_AVAILABILITY: FeedAvailability,
        PathValues.MEDIA_MATH_CHECK_TYPE: MediaMathCheckType,
        PathValues.MEDIA_MATH_FORMULA_HASH: MediaMathFormulaHash,
        PathValues.MEDIA_MATH_RENDER_FORMAT_HASH: MediaMathRenderFormatHash,
        PathValues.METRICS_BYTESDIFFERENCE_ABSOLUTE_AGGREGATE_PROJECT_EDITORTYPE_PAGETYPE_GRANULARITY_START_END: MetricsBytesDifferenceAbsoluteAggregateProjectEditorTypePageTypeGranularityStartEnd,
        PathValues.METRICS_BYTESDIFFERENCE_ABSOLUTE_PERPAGE_PROJECT_PAGETITLE_EDITORTYPE_GRANULARITY_START_END: MetricsBytesDifferenceAbsolutePerPageProjectPageTitleEditorTypeGranularityStartEnd,
        PathValues.METRICS_BYTESDIFFERENCE_NET_AGGREGATE_PROJECT_EDITORTYPE_PAGETYPE_GRANULARITY_START_END: MetricsBytesDifferenceNetAggregateProjectEditorTypePageTypeGranularityStartEnd,
        PathValues.METRICS_BYTESDIFFERENCE_NET_PERPAGE_PROJECT_PAGETITLE_EDITORTYPE_GRANULARITY_START_END: MetricsBytesDifferenceNetPerPageProjectPageTitleEditorTypeGranularityStartEnd,
        PathValues.METRICS_EDITEDPAGES_AGGREGATE_PROJECT_EDITORTYPE_PAGETYPE_ACTIVITYLEVEL_GRANULARITY_START_END: MetricsEditedPagesAggregateProjectEditorTypePageTypeActivityLevelGranularityStartEnd,
        PathValues.METRICS_EDITEDPAGES_NEW_PROJECT_EDITORTYPE_PAGETYPE_GRANULARITY_START_END: MetricsEditedPagesNewProjectEditorTypePageTypeGranularityStartEnd,
        PathValues.METRICS_EDITEDPAGES_TOPBYABSOLUTEBYTESDIFFERENCE_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditedPagesTopByAbsoluteBytesDifferenceProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITEDPAGES_TOPBYEDITS_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditedPagesTopByEditsProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITEDPAGES_TOPBYNETBYTESDIFFERENCE_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditedPagesTopByNetBytesDifferenceProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITORS_AGGREGATE_PROJECT_EDITORTYPE_PAGETYPE_ACTIVITYLEVEL_GRANULARITY_START_END: MetricsEditorsAggregateProjectEditorTypePageTypeActivityLevelGranularityStartEnd,
        PathValues.METRICS_EDITORS_TOPBYABSOLUTEBYTESDIFFERENCE_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditorsTopByAbsoluteBytesDifferenceProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITORS_TOPBYEDITS_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditorsTopByEditsProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITORS_TOPBYNETBYTESDIFFERENCE_PROJECT_EDITORTYPE_PAGETYPE_YEAR_MONTH_DAY: MetricsEditorsTopByNetBytesDifferenceProjectEditorTypePageTypeYearMonthDay,
        PathValues.METRICS_EDITS_AGGREGATE_PROJECT_EDITORTYPE_PAGETYPE_GRANULARITY_START_END: MetricsEditsAggregateProjectEditorTypePageTypeGranularityStartEnd,
        PathValues.METRICS_EDITS_PERPAGE_PROJECT_PAGETITLE_EDITORTYPE_GRANULARITY_START_END: MetricsEditsPerPageProjectPageTitleEditorTypeGranularityStartEnd,
        PathValues.METRICS_LEGACY_PAGECOUNTS_AGGREGATE_PROJECT_ACCESSSITE_GRANULARITY_START_END: MetricsLegacyPagecountsAggregateProjectAccessSiteGranularityStartEnd,
        PathValues.METRICS_PAGEVIEWS_AGGREGATE_PROJECT_ACCESS_AGENT_GRANULARITY_START_END: MetricsPageviewsAggregateProjectAccessAgentGranularityStartEnd,
        PathValues.METRICS_PAGEVIEWS_PERARTICLE_PROJECT_ACCESS_AGENT_ARTICLE_GRANULARITY_START_END: MetricsPageviewsPerArticleProjectAccessAgentArticleGranularityStartEnd,
        PathValues.METRICS_PAGEVIEWS_TOPBYCOUNTRY_PROJECT_ACCESS_YEAR_MONTH: MetricsPageviewsTopByCountryProjectAccessYearMonth,
        PathValues.METRICS_PAGEVIEWS_TOP_PROJECT_ACCESS_YEAR_MONTH_DAY: MetricsPageviewsTopProjectAccessYearMonthDay,
        PathValues.METRICS_REGISTEREDUSERS_NEW_PROJECT_GRANULARITY_START_END: MetricsRegisteredUsersNewProjectGranularityStartEnd,
        PathValues.METRICS_UNIQUEDEVICES_PROJECT_ACCESSSITE_GRANULARITY_START_END: MetricsUniqueDevicesProjectAccessSiteGranularityStartEnd,
        PathValues.TRANSFORM_HTML_FROM_FROM_LANG_TO_TO_LANG: TransformHtmlFromFromLangToToLang,
        PathValues.TRANSFORM_HTML_FROM_FROM_LANG_TO_TO_LANG_PROVIDER: TransformHtmlFromFromLangToToLangProvider,
        PathValues.TRANSFORM_LIST_TOOL_TOOL: TransformListToolTool,
        PathValues.TRANSFORM_LIST_TOOL_TOOL_FROM: TransformListToolToolFrom,
        PathValues.TRANSFORM_LIST_TOOL_TOOL_FROM_TO: TransformListToolToolFromTo,
        PathValues.TRANSFORM_WORD_FROM_FROM_LANG_TO_TO_LANG_WORD: TransformWordFromFromLangToToLangWord,
        PathValues.TRANSFORM_WORD_FROM_FROM_LANG_TO_TO_LANG_WORD_PROVIDER: TransformWordFromFromLangToToLangWordProvider,
        PathValues.TRANSFORM_LIST_LANGUAGEPAIRS: TransformListLanguagepairs,
        PathValues.TRANSFORM_LIST_PAIR_FROM_TO: TransformListPairFromTo,
    }
)
