from wikimedia_python_sdk.paths.metrics_editors_top_by_absolute_bytes_difference_project_editor_type_page_type_year_month_day.get import ApiForget


class MetricsEditorsTopByAbsoluteBytesDifferenceProjectEditorTypePageTypeYearMonthDay(
    ApiForget,
):
    pass
