from wikimedia_python_sdk.paths.metrics_bytes_difference_absolute_aggregate_project_editor_type_page_type_granularity_start_end.get import ApiForget


class MetricsBytesDifferenceAbsoluteAggregateProjectEditorTypePageTypeGranularityStartEnd(
    ApiForget,
):
    pass
