from wikimedia_python_sdk.paths.metrics_editors_aggregate_project_editor_type_page_type_activity_level_granularity_start_end.get import ApiForget


class MetricsEditorsAggregateProjectEditorTypePageTypeActivityLevelGranularityStartEnd(
    ApiForget,
):
    pass
