# coding: utf-8

"""
    Wikimedia

    This API provides cacheable and straightforward access to Wikimedia content and data, in machine-readable formats. ### Global Rules - Limit your clients to no more than 200 requests/s to this API.   Each API endpoint's documentation may detail more specific usage limits. - Set a unique `User-Agent` or `Api-User-Agent` header that   allows us to contact you quickly. Email addresses or URLs   of contact pages work well.  By using this API, you agree to Wikimedia's  [Terms of Use](https://wikimediafoundation.org/wiki/Terms_of_Use) and [Privacy Policy](https://wikimediafoundation.org/wiki/Privacy_policy). Unless otherwise specified in the endpoint documentation below, content accessed via this API is licensed under the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)  and [GFDL](https://www.gnu.org/copyleft/fdl.html) licenses, and you irrevocably agree to release modifications or additions made through this API under these licenses.  See https://www.mediawiki.org/wiki/REST_API for background and details. ### Endpoint documentation Please consult each endpoint's documentation for details on: - Licensing information for the specific type of content   and data served via the endpoint. - Stability markers to inform you about development status and   change policy, according to   [our API version policy](https://www.mediawiki.org/wiki/API_versioning). - Endpoint specific usage limits. 

    The version of the OpenAPI document: 1.0.0
    Created by: http://mediawiki.org/wiki/REST_API
"""

from wikimedia_python_sdk.paths.metrics_edited_pages_aggregate_project_editor_type_page_type_activity_level_granularity_start_end.get import GetAggregateByProjectAndDateRangeRaw
from wikimedia_python_sdk.paths.metrics_edited_pages_new_project_editor_type_page_type_granularity_start_end.get import GetNewPagesCountsForProjectRaw
from wikimedia_python_sdk.paths.metrics_edited_pages_top_by_absolute_bytes_difference_project_editor_type_page_type_year_month_day.get import GetTopByAbsoluteBytesDifferenceRaw
from wikimedia_python_sdk.paths.metrics_edited_pages_top_by_edits_project_editor_type_page_type_year_month_day.get import GetTopByEditsCountRaw
from wikimedia_python_sdk.paths.metrics_edited_pages_top_by_net_bytes_difference_project_editor_type_page_type_year_month_day.get import GetTopByNetBytesDifferenceRaw


class EditedPagesDataApiRaw(
    GetAggregateByProjectAndDateRangeRaw,
    GetNewPagesCountsForProjectRaw,
    GetTopByAbsoluteBytesDifferenceRaw,
    GetTopByEditsCountRaw,
    GetTopByNetBytesDifferenceRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
